// <auto-generated />
using GotMilkWeed;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GotMilkWeed.Migrations
{
    [DbContext(typeof(MilkweedDbContext))]
    [Migration("20230322234317_seed_data")]
    partial class seed_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("GotMilkWeed.MilkweedVariety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsToxicToMonarchs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("milkweedVarieties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsToxicToMonarchs = true,
                            Name = "Common Milkweed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 2,
                            IsToxicToMonarchs = false,
                            Name = "Butterfly Weed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 3,
                            IsToxicToMonarchs = false,
                            Name = "Swamp Milkweed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 4,
                            IsToxicToMonarchs = true,
                            Name = "Showy Butterfly",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 5,
                            IsToxicToMonarchs = true,
                            Name = "Whorled Milkweed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 6,
                            IsToxicToMonarchs = false,
                            Name = "Green Milkweed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 7,
                            IsToxicToMonarchs = true,
                            Name = "Antelope Horns",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 8,
                            IsToxicToMonarchs = true,
                            Name = "Purple Milkweed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 9,
                            IsToxicToMonarchs = false,
                            Name = "Sand Milkweed",
                            Region = "North American"
                        },
                        new
                        {
                            Id = 10,
                            IsToxicToMonarchs = true,
                            Name = "Red Milkweed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 11,
                            IsToxicToMonarchs = true,
                            Name = "Poke Milkweed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 12,
                            IsToxicToMonarchs = false,
                            Name = "Texas Milkweed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 13,
                            IsToxicToMonarchs = true,
                            Name = "Sullivants Milkweed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 14,
                            IsToxicToMonarchs = true,
                            Name = "Horsetail Milkweed",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 15,
                            IsToxicToMonarchs = true,
                            Name = "Clasping Milkweed",
                            Region = "North America"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
